### ISSUE TITLE
Can not install with pipenv

### ISSUE THREAD

**Issue by dbinetti** [kennethreitz/maya#121]
I can't be the only one experiencing this, can I?  Lockfile attached

MacOS 10.13.3
Python 3.6.4
Pipenv 9.0.3

```
(barberscore-api)$ pipenv install maya
Installing maya…
Collecting maya
  Using cached maya-0.3.3-py2.py3-none-any.whl
Collecting dateparser (from maya)
  Using cached dateparser-0.7.0-py2.py3-none-any.whl
Collecting pendulum (from maya)
  Using cached pendulum-1.4.1-cp36-cp36m-macosx_10_13_x86_64.whl
Collecting ruamel.yaml (from maya)
Requirement already satisfied: pytz in ./.venv/lib/python3.6/site-packages (from maya)
Collecting tzlocal (from maya)
Collecting humanize (from maya)
Requirement already satisfied: python-dateutil in ./.venv/lib/python3.6/site-packages (from dateparser->maya)
Collecting regex (from dateparser->maya)
Collecting pytzdata (from pendulum->maya)
  Using cached pytzdata-2018.3-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.6/site-packages (from python-dateutil->dateparser->maya)
Installing collected packages: regex, tzlocal, dateparser, pytzdata, pendulum, ruamel.yaml, humanize, maya
Successfully installed dateparser-0.7.0 humanize-0.5.1 maya-0.3.3 pendulum-1.4.1 pytzdata-2018.3 regex-2018.2.8 ruamel.yaml-0.15.35 tzlocal-1.5.1

Adding maya to Pipfile's [packages]…
  PS: You have excellent taste! ✨ 🍰 ✨
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
An unexpected error occurred while accessing your virtualenv's python installation!
Please run $ pipenv --rm to re-create your environment.
(barberscore-api)$ pipenv --rm
Removing virtualenv (/Users/dbinetti/repos/barberscore-api/.venv)…
(barberscore-api)$ pipenv install --dev
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/dbinetti/repos/barberscore-api/.venv/bin/python3.6
Also creating executable in /Users/dbinetti/repos/barberscore-api/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/dbinetti/repos/barberscore-api/.venv
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (699501)!
Installing dependencies from Pipfile.lock (699501)…
An error occurred while installing astroid==1.6.1! Will try again.
An error occurred while installing attrs==17.4.0! Will try again.
An error occurred while installing autopep8==1.3.4! Will try again.
An error occurred while installing django==2.0.2! Will try again.
An error occurred while installing django-debug-toolbar==1.9.1! Will try again.
An error occurred while installing factory-boy==2.10.0! Will try again.
An error occurred while installing faker==0.8.11! Will try again.
An error occurred while installing graphviz==0.8.2! Will try again.
An error occurred while installing isort==4.3.4! Will try again.
An error occurred while installing lazy-object-proxy==1.3.1! Will try again.
An error occurred while installing mccabe==0.6.1! Will try again.
An error occurred while installing pluggy==0.6.0! Will try again.
An error occurred while installing py==1.5.2! Will try again.
An error occurred while installing pycodestyle==2.3.1! Will try again.
An error occurred while installing pydocstyle==2.1.1! Will try again.
An error occurred while installing pylint==1.8.2! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 106/106 — 00:01:28
An error occurred while installing pytest==3.4.0! Will try again.
An error occurred while installing pytest-django==3.1.2! Will try again.
An error occurred while installing python-dateutil==2.6.1! Will try again.
An error occurred while installing pytz==2018.3! Will try again.
An error occurred while installing six==1.11.0! Will try again.
An error occurred while installing snowballstemmer==1.2.1! Will try again.
An error occurred while installing sqlparse==0.2.4! Will try again.
An error occurred while installing text-unidecode==1.1! Will try again.
An error occurred while installing wrapt==1.10.11! Will try again.
An error occurred while installing git+git://github.com/barberscore/django-fsm-log.git#egg=django-fsm-log! Will try again.
Installing initially–failed dependencies…
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/26 — 00:00:00
Failed to import the site module
Traceback (most recent call last):
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 703, in <module>
    main()
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/dbinetti/repos/barberscore-api/.venv/bin/../lib/python3.6/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/types.py", line 6, in <module>
    import functools as _functools
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/functools.py", line 24, in <module>
    from types import MappingProxyType
ImportError: cannot import name 'MappingProxyType'

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/26 — 00:00:00
(barberscore-api)$ 
```

**Comment by dbinetti** [comment]
[Pipfile.lock.txt](https://github.com/kennethreitz/maya/files/1737707/Pipfile.lock.txt)

**Comment by dbinetti** [comment]
And still fails on 9.1, but this seems to be a different error.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==9.1.0', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 235, in uninstall
    verbose=verbose
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/core.py", line 1888, in do_uninstall
    do_lock(system=system, pre=pre)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/core.py", line 1113, in do_lock
    allow_global=system
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/utils.py", line 340, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/utils.py", line 301, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/pipenv/9.1.0/libexec/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/03/mg213wc514s0jndlht55pcd00000gn/T/tmpqpunm37kbuild/regex/
```

**Comment by dbinetti** [comment]
Oh, and it bricked the pipenv environment itself -- need to remove an rebuild

```
Davids-MacBook:barberscore-api dbinetti$ pipenv uninstall maya
Un-installing maya…

Removing maya from Pipfile…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
An unexpected error occurred while accessing your virtualenv's python installation!
Please run $ pipenv --rm to re-create your environment.
````

**Comment by dbinetti** [comment]
Fixed with pipenv 10.1.0

**Comment by dbinetti** [comment]
Temporarily fixed, apparently.  When I tried to add another library same thing -- and it bricks the whole .venv.
