### ISSUE TITLE
MayaInterval unable to parse from ISO 8601

### ISSUE THREAD

**Issue by matmunn** [kennethreitz/maya#123]
When trying to initialise a MayaInterval object from an ISO 8601 string it always fails with a TypeError:
```
TypeError: unorderable types: MayaDT() == str()
```

I've included the full stack trace below, it seems to be a problem with how Pendulum is parsing the string.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/lib/python2.7/site-packages/maya/core.py", line 395, in from_iso8601
    end = parse(start)
  File "/code/lib/python2.7/site-packages/maya/core.py", line 646, in parse
    dt = pendulum.parse(string, **options)
  File "/code/lib/python2.7/site-packages/pendulum/parser.py", line 75, in parse
    return Parser(**options).parse(text)
  File "/code/lib/python2.7/site-packages/pendulum/parser.py", line 28, in parse
    if text == 'now':
  File "/code/lib/python2.7/site-packages/maya/core.py", line 38, in wrapper
    type(self).__name__, operator, type(arg).__name__))
TypeError: unorderable types: MayaDT() == str()
```

**Comment by matmunn** [comment]
I also just realised that I am playing with a function that by default raises a NotImplementedError so I'm going to close this for now.
