### ISSUE TITLE
How to use EPOCH_START or should it be readonly?

### ISSUE THREAD

**Issue by akash0x53** [kennethreitz/maya#26]
I can guess `EPOCH_START` is intentionally exposed. How to use it properly? I see exception and strange values on random value.

```>>> maya.EPOCH_START = (0000,1,1)
>>> maya.when("tomorrow")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akash/.pyenv/versions/vzcode/lib/python2.7/site-packages/maya.py", line 201, in when
    return MayaDT.from_datetime(dt)
  File "/home/akash/.pyenv/versions/vzcode/lib/python2.7/site-packages/maya.py", line 79, in from_datetime
    return klass(klass.__dt_to_epoch(dt))
  File "/home/akash/.pyenv/versions/vzcode/lib/python2.7/site-packages/maya.py", line 70, in __dt_to_epoch
    epoch_start = Datetime(*EPOCH_START, tzinfo=pytz.timezone('UTC'))
ValueError: year is out of range
```

and this one
```
>>> maya.EPOCH_START = (1900, 1, 1)
>>> maya.when("tomorrow")
<MayaDT epoch=3691578038.69>
>>> maya.when("tomorrow").epoch
3691578046.866085
>>> import time
>>> time.ctime(3691578046.866085)
'Tue Dec 24 19:50:46 2086'
```

**Comment by kennethreitz** [comment]
it is not exposed intentionally

**Comment by kennethreitz** [comment]
I just renamed it `_EPOCH_START` to make that more clear.
